version: '3'

services:
  snapverse:
    build: server
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://snap_verse:3306/snapverse_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: Ual110902@
    restart: always
    depends_on:
      snap_verse:
        condition: service_healthy

  snap_verse:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Ual110902@
      MYSQL_DATABASE: snapverse_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      timeout: 10s
      retries: 10
